crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream0_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream1_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream2_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream3_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream4_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream5_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream6_Mini
crab report -d crab_projects/crab_SkimB4Mu_YEAReraERANAME_stream7_Mini
